name: quran_random_ayah
description: "Quran random ayah project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  http: ^1.2.1
  provider: ^6.1.2
  google_fonts: ^6.2.1
  url_launcher: ^6.2.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  import_sorter: ^4.6.0


flutter:
  uses-material-design: true

  fonts:
    - family: Indopak_WBW
      fonts:
        - asset: fonts/AlQuran-IndoPak-by-QuranWBW.v.4.2.2-WL.ttf
    - family: Symbols-NF
      fonts:
        - asset: fonts/SymbolsNerdFont-Regular.ttf
